# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Welcome to my blog...!
title: Sofyan Hadi Ahmad
description: My place to share a share-able things
author:
  name: Sofyan Hadi Ahmad
  email: sofyan.h.ahmad@gmail.com
  skype: sofyan.h.ahmad@gmail.com
  github: sofyanhadia
  twitter: sofyan_hadi_a
  #pinterest: asd123
  linkedin: sofyanhadiahmad
  bio: A programmer who program programs to execute the program command using latest programming language to program the programmed program
  email_md5: e15a22b520d7b101bc7984b0652f174b

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
